function [binss,pdf,stanR] = makedis(inno_win,hsf,win,binsize)

stanR = [std(inno_win(1,:)); std(inno_win(2,:)); std(inno_win(3,:)); std(inno_win(4,:))];
meanR = [mean(inno_win(1,:)); mean(inno_win(2,:)); mean(inno_win(3,:)); mean(inno_win(4,:))];

binss = [       linspace(meanR(1)-5*stanR(1), meanR(1)+5*stanR(1), binsize)' ...
                linspace(meanR(2)-5*stanR(2), meanR(2)+5*stanR(2), binsize)' ...
                linspace(meanR(3)-5*stanR(3), meanR(3)+5*stanR(3), binsize)' ...
                linspace(meanR(4)-5*stanR(4), meanR(4)+5*stanR(4), binsize)'];
            
pdf =   [       predpdf(hsf,stanR(1),inno_win(1,:),win,binss(:,1)',binsize)'...
                predpdf(hsf,stanR(2),inno_win(2,:),win,binss(:,2)',binsize)'...
                predpdf(hsf,stanR(3),inno_win(3,:),win,binss(:,3)',binsize)'...
                predpdf(hsf,stanR(4),inno_win(4,:),win,binss(:,4)',binsize)'];


end